name: BarberShop CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Find project files
        run: find . -type f -name "*.csproj"
      - name: Build API
        run: dotnet build ./BarberShop.Api/BarberShop.Api.csproj -c Release
      - name: Build Worker
        run: dotnet build ./BarberShopWorker/BarberShopWorker.csproj -c Release
      - name: Build API Docker image
        run:  docker build -f BarberShop.Api/Dockerfile -t barbershop-api .
      - name: Build Worker Docker image
        run:  docker build -f BarberShopWorker/Dockerfile -t barbershop-worker .
      - name: Start RabbitMQ container
        run: docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management-alpine
      - name: Start Redis container
        run: docker run -d --name cache -p 6379:6379 redis:6.2-alpine redis-server --save 20 1 --loglevel warning
      - name: Start API container
        run: docker run -d --name barbershop-api --link rabbitmq:rabbitmq --link cache:cache -p 502:80 -p 5002:443 barbershop-api
      - name: Start Worker container
        run: docker run -d --name barbershop-worker --link rabbitmq:rabbitmq barbershop-worker
        
      - name: Upload API artifact
        uses: actions/upload-artifact@v2
        with:
          name: barbershop-api
          path: ./BarberShop.Api/bin/Release/net7.0
          
      - name: Upload Worker artifact
        uses: actions/upload-artifact@v2
        with:
          name: barbershop-worker
          path: ./BarberShopWorker/bin/Release/net7.0

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download API artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: barbershop-api
          path: ./artifacts/barbershop-api.zip
          
      - name: Display contents of downloaded artifact
        run: |
         unzip -l ./artifacts/barbershop-api.zip
         ls -al ./artifacts/barbershop-api
         
      - name: Deploy barber shop api to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'barber-shop-app'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
          package: ./artifacts/barbershop-api.zip
          
      - name: Download Worker artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: barbershop-worker
  
      - name: Display Appsettings
        run: cat appsettings.json
        
    env:
      DOTNET_ROOT: 'prod'
